### PR TITLE
[PAGE NAME] [short description, max 10 words]

### PR DESCRIPTION
**Pull request by adonisjoe**
This description should include:
- short description of your implementation - max 4-5 sentences
- link to the Trello ticket from the board
- any dependencies added, workflow changes, constraints, things to consider, etc.
- screenshots for both desktop and mobile for the layout implemented

@adonisjoe Please update the title and description accordingly

- Created A simple HTML page with responsive design where we can showcase the doctors from medical practice.
- https://trello.com/c/UJ0HeTK6/88-implement-echipa-page-on-tisamed.
- I used lightbox library to achieve photoswipe.
- Find the attached photos of different screen sizes beneath.
127 0 0 1_5501_echipa_index html(iPhone SE)
127 0 0 1_5501_echipa_index html (1)

### CODE REVIEW

**Comment by adonisjoe** [comment]
Please provide me with the required images and texts to replace the temp texts and pictures. Thanks!

**Comment by georgebrata** [comment]
Why did you created and pushed to git a **node_modules** folder? 

You have all the source code of the photo-swipe library locally, in 📄 `assets/js/photoswipe-lightbox.esm.js` and you initialise it in `[assets/js/script.js](https://github.com/georgebrata/tisamed-landing/pull/9/files#diff-4698a0d6946cc7eab0ee49f1773e6bfa66a91c8c1ae37b2587b9dc9ebdf47247)`, which is good. You don't need a **node_modules** folder so please delete it and no more `npm install ...` on simple html, css, js projects, ok?

**Comment by adonisjoe** [comment]
> This description should include:
> 
> * short description of your implementation - max 4-5 sentences
> * link to the Trello ticket from the board
> * any dependecies added, workflow changes, constraints, things to consider, etc.
> * screenshots for both desktop and mobile for the layout implemented
> 
> @adonisjoe Please update the title and description accordingly
> 
> …Showcase the expertise and profiles of our medical practice's doctors. User-friendly interface for easy navigation and exploration. Modern and sleek design to leave a lasting impression on visitors. Feel free to explore our doctor showcase page and learn more about the dedicated professionals who contribute to our medical practice's success. Your health and well-being are our priority!"
> 
> This project is a simple HTML page with a responsive design that allows us to showcase the talented doctors from our esteemed medical practice. The page layout adapts seamlessly to different screen sizes, ensuring a user-friendly experience on various devices, including desktops, tablets, and smartphones.
> 
> Key Features:
> 
> Responsive design for optimal viewing across devices. Showcase the expertise and profiles of our medical practice's doctors. User-friendly interface for easy navigation and exploration. Modern and sleek design to leave a lasting impression on visitors. Feel free to explore our doctor showcase page and learn more about the dedicated professionals who contribute to our medical practice's success. Your health and well-being are our priority!"

I have done those

**Comment by adonisjoe** [comment]
> …Showcase the expertise and

**Review by georgebrata — APPROVED** [review]
If you remove the files `package.json` and `package-lock.json` we can merge this.

**Pull request merged**
